# Generated by Django 5.2.18 on 2026-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='state',
            field=models.CharField(blank=True, help_text='Leave empty for the whole zone, or name one state to give it its own fee.', max_length=40),
        ),
    ]
