# Generated by Django 5.2.18 on 2026-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingmethod_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='pay_on_delivery',
            field=models.BooleanField(default=False, help_text='Nothing is charged at checkout; the customer pays the bus driver or park when the parcel arrives.'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='estimate',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
