# Generated by Django 5.2.18 on 2026-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_homepick'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces in one wholesale pack, e.g. 12', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.BigIntegerField(blank=True, help_text='kobo; price of one whole pack', null=True),
        ),
    ]
